defmodule UnclickbaiterWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :unclickbaiter

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_unclickbaiter_key",
    signing_salt: "reRAnUiY",
    same_site: "Lax"
  ]

  # Protect the whole site with HTTP Basic auth. Credentials are resolved
  # at request time so they can be set via environment variables at runtime
  # without recompiling.
  plug :basic_auth

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :unclickbaiter,
    gzip: not code_reloading?,
    only: UnclickbaiterWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :unclickbaiter
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug UnclickbaiterWeb.Router

  defp basic_auth(conn, _opts) do
    if Application.get_env(:unclickbaiter, :env) == :prod do
      Plug.BasicAuth.basic_auth(conn,
        username:
          Application.get_env(:unclickbaiter, :secrets)[:basic_auth][:user],
        password:
          Application.get_env(:unclickbaiter, :secrets)[:basic_auth][:pass]
      )
    else
      conn
    end
  end
end
