# mise.toml — tooling environment for this project
# Defines language/tool runtimes to be installed/used by automation.

[tools.pipx]
# Use the latest pipx available
version = "1.16.6"
# CLI packages to install globally (via pipx). Adjust as needed.
packages = [
  "gigalixir"
]

[tools.elixir]
# Request the latest Elixir release
version = "1.20.3"
# Install the latest compatible Erlang/OTP runtime
otp = "29.0.5"
# Default mix environment to use when running mix tasks
mix_env = "dev"

[tools.npm]
# Request the explicit npm release
version = "12.0.2"
# Global npm packages to install
packages = [
  "esbuild",
]
