import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :unclickbaiter, UnclickbaiterWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :unclickbaiter, UnclickbaiterWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Better Stack Logger - ships logs to Better Stack
config :logger, handlers: [
  betterstack_logs: [
    module: :betterstack_logger,
    level: :info,
    config: [
      betterstack_host:
        System.get_env("BETTERSTACK_LOG_HOST", "https://in.logs.betterstack.com"),
      betterstack_source_token: System.get_env("BETTERSTACK_LOG_SOURCE_TOKEN"),
      extra_fields: [env: "prod"],
      upload_batch_max_size: 50,
      upload_batch_interval_ms: 5000,
      upload_failed_retry_count: 3,
      upload_failed_retry_delay_ms: 1000
    ]
  ]
]

# Sentry (Better Stack Error Tracking) - Sentry-compatible DSN
config :sentry,
  dsn: System.get_env("BETTERSTACK_SENTRY_DSN"),
  environment_name: "prod",
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()],
  tags: %{
    env: "prod"
  },
  included_environments: [:prod]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
